# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Deploy Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/outdoor-identity:latest ./src/Identity.API
          docker push ${{ secrets.DOCKER_USERNAME }}/outdoor-identity:latest

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Remote Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/outdoor-identity:latest
            docker stop outdoor-identity || true
            docker rm outdoor-identity || true
            docker run -d \
              --name outdoor-identity \
              -p 8080:8080 \
              -e ASPNETCORE_ENVIRONMENT=Production \
              -e ConnectionStrings__Default="${{ secrets.DB_CONNECTION }}" \
              -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESSKEY }}" \
              -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRETKEY }}" \
              ${{ secrets.DOCKER_USERNAME }}/outdoor-identity:latest